- name: Install base packages with Homebrew (macOS)
  community.general.homebrew:
    name:
      - git
      - wget
      - curl
      - ripgrep
      - tmux
      - neovim
      - lazygit
    state: present
    update_homebrew: false
  when: ansible_system == 'Darwin'
  vars:
    # Needed for cask fonts
    homebrew_taps:
      - homebrew/cask-fonts

- name: Tap additional Homebrew repositories
  community.general.homebrew_tap:
    name: "{{ item }}"
    state: present
  loop: [ 'homebrew/cask-fonts' ]
  when: ansible_system == 'Darwin'

- name: Install fonts via Homebrew cask (macOS)
  community.general.homebrew_cask:
    name:
      - font-jetbrains-mono-nerd-font
    state: present
  when: ansible_system == 'Darwin'
