#SPDX-License-Identifier: MIT-0
---
# tasks file for smart-keys
- name: Install the 'Development tools' package group
  ansible.builtin.dnf:
    name: '@Development Tools'
    state: present
  become: true
- name: Install keyd from source
  git:
    repo: https://github.com/rvaiya/keyd
    dest: "{{ lookup('env', 'HOME') }}/Applications/keyd"
    version: master
- name: Build keyd
  community.general.make:
    chdir: "{{ lookup('env', 'HOME') }}/Applications/keyd"
- name: Run 'install' as root
  become: true
  community.general.make:
    chdir: "{{ lookup('env', 'HOME') }}/Applications/keyd"
    target: install
- name: Install default.conf
  copy:
    src: files/default.conf
    dest: /etc/keyd/default.conf
    backup: true
  become: true
  notify:
    - Enable and start keyd